FROM nginx:alpine

# override entrypoint in built docker container
# nginx Dockerfile https://github.com/nginxinc/docker-nginx/blob/e117bd83e9befe5582bc1da8f72248398fffa16c/mainline/alpine/Dockerfile

ENTRYPOINT "sh"
